### ISSUE TITLE
Port to 11.2

### ISSUE THREAD

**Issue by izobilje** [wesleywerner/nova-pinball#6]
Perhaps merge https://github.com/wrldwzrd89/nova-pinball

**Comment by retropipes** [comment]
I have created the relevant PRs to do exactly this.

**Comment by wesleywerner** [comment]
Thanks for this @wrldwzrd89. I see you changed the submodule path to your repo, not a bad thing in itself, however that splits the engine into two forks - which is valid if the two versions diverge in features. But since this is an upgrade path it would be good to have a PR for the engine, and a PR for the game itself.

I am making a note to look into creating an engine PR from your fork, and resolving the submodule paths to the same. When all is said and done, your forks (both engine and game) should be inline with upstream.

I will also add a contributor section to the readme. How do you want to be credited @wrldwzrd89?

**Comment by retropipes** [comment]
There is a separate PR to upgrade the engine too, since that's also needed, in that repo. I've never been asked for credit preference before, so I therefore have none.

**Comment by wesleywerner** [comment]
These changes are now merged. Thanks folks!
